### ISSUE TITLE
Learner selection & construction

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr_shiny#1]

**Comment by berndbischl** [comment]
for classif: i would always set the predict type to "prob", i dont think there is a downside to this

**Comment by berndbischl** [comment]
what is harder is how we let the user select the params

**Comment by berndbischl** [comment]
IMHO the learners should be selected on their own page? 
they already seem to influence multiple things?

**Comment by jakob-r** [comment]
IMHO we have three options
1) Let the user enter the par.vals list directly
2) Have some hand coded interfaces for the most popular learners
3) Parse the par.set of the Learner and generate a shiny UI based on that. For every param type there will be a specific sidebarPanel and so on. Tedious but doable

**Comment by berndbischl** [comment]
how about we have a textbox per selected learner, where the user enters the parvals, simply as an expression. thats simple, but flexible. but while that learner is in focus / selected, we also display its param set. so i can see how stuff is named / called. 

later on the UI could be improved.

**Comment by PhilippPro** [comment]
there are learners like kknn that do not have the property "prob"

On the three options: I would prefer option 3. Maybe the interface for the parameters could be created automatically after setting an algorithm (e.g. with help of getParamSet). I do not know if this is possible in shiny.

**Comment by berndbischl** [comment]
> On the three options: I would prefer option 3. Maybe the interface for the parameters could be created automatically after setting an algorithm (e.g. with help of getParamSet). I do not know if this is possible in shiny.

of course one can program this, also with shiny. but it will be work. i would suggest to do the simpler thing first....

**Comment by florianfendt** [comment]
Since #24 we have a learner tab, where all learners for the ongoing steps are selected and constructed.
For each learner the user can see the ParamSet and then enter the par.vals as raw text.
If a classification learner supports probs the user can select the predict type.
Next steps:
-  implement sliders and buttons for the different param types
- Allow predict.type = "se" for regression learners

**Comment by Coorsaa** [comment]
just found a small bug: when changing a param of a learner in the learner section, automatically the tab of the first learner is selected again.

**Comment by Coorsaa** [comment]
this issue seems to be obsolete since PR #63
