### ISSUE TITLE
File/Folder management

### ISSUE THREAD

**Issue by florianfendt** [mlr-org/mlr_shiny#100]
We're having quite some files in the root directory now and I'm sometimes a bit annoyed when looking for a file a couple of seconds 😄 
Probably there are not much more files to be added in the near future but I would vote for separating the files better by restructuring a bit. Maybe sth like this:
* helpers (ideally with renaming helper files to `tabName_helpers.R`
* server
* ui
* new file `app.R` in the root directory

Here's a minimal example:
https://github.com/daattali/advanced-shiny/tree/master/split-code

@Coorsaa what do you reckon?

**Comment by florianfendt** [comment]
Also:
* We have server_data_summary.R, ui_tabpanel_summary.R, ui_tabpanel_preprocessing.R, bit confusing to me.
* server_visualisation.R is debatable. On the one hand we could argue that it makes more sense to have all the plotting reactives in one file (then we should move the prediction plots there as well though). On the other side (for which I'd vote) put the different plotting  reactives in the corresponding sections.
Imho it's a) clearer where it's used and b) minimizes the danger of overseeing dependencies to the plotting parts when we work at sth

**Comment by Coorsaa** [comment]
@florianfendt 
yes, we should definitely reorder all these files into folders and subfolders...
You're right with data summary and preproc. We should add a server_preproc analogue to the ui file.
 Also the server_visualisation is confusing since it uses the functions of the server_helper_train_and_predict for its plots.

**Comment by florianfendt** [comment]
done in #103
