### ISSUE TITLE
Visualisations: make it conditional on the task

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr_shiny#16]
Show the respective visualisation tool only if accessible. (e.g. ROC Analysis only available for binary classification)

**Comment by larskotthoff** [comment]
I'm not sure what you mean with this. Have a `listPlots()` function?

**Comment by PhilippPro** [comment]
Yes something like that (listPlots(task)). And then only show it in the navbarmenu, if it makes sense.
