### ISSUE TITLE
Implement data preprocessing

### ISSUE THREAD

**Issue by florianfendt** [mlr-org/mlr_shiny#33]
Make a new tab where the user can see a quick summary of the data, like:
Any Na's, constant features etc.
Then make preprocessing available with help of impute, capLargeValues etc.

**Comment by florianfendt** [comment]
@Coorsaa 
I really like how it turned out. Couple of minor things I noticed though:
* For Drop variables the slider input also says choose target. Should be choose columns/features.
Also set ``multiple`` to ``TRUE``. Then we can drop multiple columns at once without clicking the button again and again.
* For impute we always select one imputation method for a whole class. Maybe the user wants different imputation techniques for specific features. In mlr this is achieved with the ``cols`` argument. Implementing this would be tedious I guess. But we could use the following workaround: Make a new ``selectInput`` "exclude columns" and add these columns to the ``target``argument of impute. This way the user can use any imputation method for any column. Downside: Action Button needs to be clicked several times.
* Rather a design perspective: I think we should separate the inputs "choose method" and "target" from the method specific inputs a bit. Because right now it's not immediately visible for the user what inputs belong to the currently selected preproc method. Either separate by columns or make some space between the rows. What do you think?

**Comment by Coorsaa** [comment]
closed by #50
