### ISSUE TITLE
convert functions as.factor(), as.numeric()

### ISSUE THREAD

**Issue by Coorsaa** [mlr-org/mlr_shiny#44]
we should add those for data preprocessing. I would suggest to add them directly as further preprocessing methods. Do u agree @florianfendt ?

**Comment by florianfendt** [comment]
Also ``joinClassLevels``and ``mergeSmallFactorLevels`` would be nice to have
Maybe all combined in one box so we don't blow up ``input$preproc_method`` too much
(possible name: recode columns)
What do you reckon?

**Comment by Coorsaa** [comment]
Sounds good. Will have a look at this tomorrow.

**Comment by Coorsaa** [comment]
unfortunately, for ````joinClassLevels```` and ````mergeSmallFactorLevels```` we need a task first. So should we add those functions in the task section? Would it be useful to have a S3 method for data.frames for both functions directly in mlr?
