### ISSUE TITLE
cannot create another task after changing or preprocessing data 

### ISSUE THREAD

**Issue by Coorsaa** [mlr-org/mlr_shiny#51]

**Comment by florianfendt** [comment]
that's not good. I'll fix it now

**Comment by florianfendt** [comment]
hold on. Can you tell me more when you encountered this?
E.G when i use the some toy tasks, drop some variables and play around with capLargeValues a bit everything works fine.

**Comment by Coorsaa** [comment]
I think it's not working any more when importing a csv file.

**Comment by florianfendt** [comment]
Mhm that's super weird to me at first glance. Everything is fine for all types except CSV. Actually one can't even create the task anymore regardless of using preproc or not.
We need to find out fast what caused this.

**Comment by florianfendt** [comment]
Just fixed it on master. Tasks where actually still created but task data was not equal to data if we had NA's in it, because we had an ``na.omit`` where we create the tasks. Simply removed it because we can now handle missing values with preprocessing.
