### ISSUE TITLE
Move dashboard sideboard to the top

### ISSUE THREAD

**Issue by florianfendt** [mlr-org/mlr_shiny#53]
I now agree with @PhilippPro that we should rather move the sidebar to the top. I see at least 2 reasons why this is better:

* When we have data with many variables we can fit more on the screen. Also for example in the predict panel the pagination bar beneath the dataTables produces ugly lines breaks, which shouldn't happen anymore the other way.
(**Update:** The latter issue i quick fixed with ``pagingType = "simple"`` I think in that spot with can live with that)
* Secondly, and maybe the more important one: On mobile devices the sidebar pushes the content of the body to the right. Especially on smaller screens it can get a real pain to use the app. (Sure we don't really support mobile use properly so far, but that day will come eventually right?)

I didn't dive deeply into the topic so far but after googling 5min it doesn't seem trivial to move the dashboardSidebar to the top. Maybe we need to find a smart way using CSS or we need to switch back to navlistBar (which is hopefully easy integrateable with the rest of the shinydashboard layout ).

**Comment by Coorsaa** [comment]
It's possible to hide the sidebar. Shouldn't this solve at least the problems on smaller screens? Is it possible to insert a scroll bar at the bottom?

**Comment by florianfendt** [comment]
We decided to leave the sidebar on the left for now.

**Comment by florianfendt** [comment]
Reopening here because I just found (rather by accident 😄) this super nice package:
[flexdashboard](http://rmarkdown.rstudio.com/flexdashboard/)
I didn't dig into it very deep but I think it should be easy to integrate that in our existing shinydashboard-theme.
I think to have the main navbar on the top makes even more sense now, since we have decided to have a sidebar for the "main" inputs of each panel.
@Coorsaa 
opinions? Do you reckon we should (at least try to) do this before our talk?

**Comment by florianfendt** [comment]
connected to #113

**Comment by florianfendt** [comment]
Can be closed. We have a new theme now :)
