### ISSUE TITLE
Bug in train panel when parameter of learner is changed and trained again

### ISSUE THREAD

**Issue by florianfendt** [mlr-org/mlr_shiny#59]

**Comment by Coorsaa** [comment]
I'm still facing the following bug:
when I train a model without probailitiy estimation and predict it. I get a data table with only truth and response as it should be. If I decide afterwards, to set prob to "yes", train the model again, and predict it afterwards, I still get only truth and response values, but no probabilities.

**Comment by florianfendt** [comment]
This bug is super weird to me. Did you notice it only happens for the randomForest? The other learners are all fine (I checked like 5-6)
