### ISSUE TITLE
Hyperparametersettings Panels too big

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr_shiny#96]
I am really impressed about the functionalities and appearance of the App. Even an automatic report system!

One small thing that bothered me, when testing, was that the Panels for the hyperparameters are too big. You maybe have to scroll down a lot if you search a specific hyperparameter.

**Comment by berndbischl** [comment]
Well we are all professionals here :)

**Comment by jakob-r** [comment]
I really hope to see you guys at the useR. It's gonna be yudge!

**Comment by florianfendt** [comment]
@PhilippPro @jakob-r 
Thanks so much guys. @Coorsaa and me are very delighted you like our work!
* As for the Hyperparameter boxes: We agree and will fiddle around with it a bit to make it more user friendly.
* Concerning UseR, @Coorsaa and me will definitely apply for this in the next week!
* Sidenote: We will present this app in a talk at LMU between the 28.2 - 4.3. This is also the week the OpenML workshop is happening at our Department. If you happen to be here for this, everybody is very welcome to join. Exact date and room will be finalized next week.

**Comment by berndbischl** [comment]
@PhilippPro will be at the OML WS
@jakob-r is here the week after, at mlr WS, so will automatically meet him, too

**Comment by PhilippPro** [comment]
I thought I wanted to be in Köln this special week... ;)

**Comment by berndbischl** [comment]
> I thought I wanted to be in Köln this special week... ;)

i cannot parse this sentence?
